apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-java-demo
  namespace: dev
spec:
  template:
    metadata:
      labels:
        app: jenkins-java-demo
    spec:
      containers:
      - image: fzhydocker/java:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-java-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-java-demo
  namespace: dev
  labels:
    app: jenkins-java-demo
spec:
  selector:
    app: jenkins-java-demo
  type: NodePort
  ports:
  - name: jenkins-java-demo
    port: 8080
    targetPort: 8080
